//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMonitor.Client.ConsumptionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsumptionDto", Namespace="http://schemas.datacontract.org/2004/07/CarMonitor.Service.Dto")]
    [System.SerializableAttribute()]
    public partial class ConsumptionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AvgConsumptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AvgPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FuelVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LastConsumptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PricePerLitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AvgConsumption {
            get {
                return this.AvgConsumptionField;
            }
            set {
                if ((this.AvgConsumptionField.Equals(value) != true)) {
                    this.AvgConsumptionField = value;
                    this.RaisePropertyChanged("AvgConsumption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AvgPrice {
            get {
                return this.AvgPriceField;
            }
            set {
                if ((this.AvgPriceField.Equals(value) != true)) {
                    this.AvgPriceField = value;
                    this.RaisePropertyChanged("AvgPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((this.DistanceField.Equals(value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FuelVolume {
            get {
                return this.FuelVolumeField;
            }
            set {
                if ((this.FuelVolumeField.Equals(value) != true)) {
                    this.FuelVolumeField = value;
                    this.RaisePropertyChanged("FuelVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LastConsumption {
            get {
                return this.LastConsumptionField;
            }
            set {
                if ((this.LastConsumptionField.Equals(value) != true)) {
                    this.LastConsumptionField = value;
                    this.RaisePropertyChanged("LastConsumption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PricePerLitre {
            get {
                return this.PricePerLitreField;
            }
            set {
                if ((this.PricePerLitreField.Equals(value) != true)) {
                    this.PricePerLitreField = value;
                    this.RaisePropertyChanged("PricePerLitre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsumptionServiceReference.IConsumptionService")]
    public interface IConsumptionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumptionService/FindByProfile", ReplyAction="http://tempuri.org/IConsumptionService/FindByProfileResponse")]
        CarMonitor.Client.ConsumptionServiceReference.ConsumptionDto[] FindByProfile(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumptionService/FindByProfile", ReplyAction="http://tempuri.org/IConsumptionService/FindByProfileResponse")]
        System.Threading.Tasks.Task<CarMonitor.Client.ConsumptionServiceReference.ConsumptionDto[]> FindByProfileAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumptionService/Add", ReplyAction="http://tempuri.org/IConsumptionService/AddResponse")]
        void Add(CarMonitor.Client.ConsumptionServiceReference.ConsumptionDto consumption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumptionService/Add", ReplyAction="http://tempuri.org/IConsumptionService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(CarMonitor.Client.ConsumptionServiceReference.ConsumptionDto consumption);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsumptionServiceChannel : CarMonitor.Client.ConsumptionServiceReference.IConsumptionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsumptionServiceClient : System.ServiceModel.ClientBase<CarMonitor.Client.ConsumptionServiceReference.IConsumptionService>, CarMonitor.Client.ConsumptionServiceReference.IConsumptionService {
        
        public ConsumptionServiceClient() {
        }
        
        public ConsumptionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsumptionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumptionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumptionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarMonitor.Client.ConsumptionServiceReference.ConsumptionDto[] FindByProfile(string name) {
            return base.Channel.FindByProfile(name);
        }
        
        public System.Threading.Tasks.Task<CarMonitor.Client.ConsumptionServiceReference.ConsumptionDto[]> FindByProfileAsync(string name) {
            return base.Channel.FindByProfileAsync(name);
        }
        
        public void Add(CarMonitor.Client.ConsumptionServiceReference.ConsumptionDto consumption) {
            base.Channel.Add(consumption);
        }
        
        public System.Threading.Tasks.Task AddAsync(CarMonitor.Client.ConsumptionServiceReference.ConsumptionDto consumption) {
            return base.Channel.AddAsync(consumption);
        }
    }
}
